# Generated by Django 3.0.5 on 2020-12-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=5)),
                ('limite', models.FloatField(max_length=3)),
                ('saldo', models.FloatField(max_length=6)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('valor', models.FloatField(max_length=6)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='Cliente.Cliente')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Conta')),
            ],
        ),
    ]
