# Generated by Django 3.0.5 on 2020-12-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='num',
            new_name='numero',
        ),
    ]
