# Generated by Django 3.0.5 on 2020-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_auto_20201218_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='limite',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.FloatField(),
        ),
    ]
